server:
  port: ${MS_USER_GROUP_SERVER_PORT:8080}

spring:
  application:
    name: "selc-user-group"
    version: "1.0-SNAPSHOT"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN

info:
  build:
    artifact: "selc-user-group"
    name: "selc-user-group"
    description: "Microservice to manage Self Care User GRoup"
    version: "1.0-SNAPSHOT"


logging:
  level:
    it.pagopa.selfcare: ${MS_USER_GROUP_LOG_LEVEL:DEBUG}
