image:
  repository: selcuacr.azurecr.io/selfcaremsusergroup
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.uat.selfcare.pagopa.it
      secretName: selc-internal-uat-selfcare-pagopa-it
  hosts:
    - host: selc.internal.uat.selfcare.pagopa.it
      paths:
        - path: /ms-user-group/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: "400m"
    memory: "700M"
  limits:
    cpu: "800m"
    memory: "800M"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_USER_GROUP_LOG_LEVEL: "INFO"