image:
  repository: selcpacr.azurecr.io/selfcaremsusergroup
  pullPolicy: Always
  tag: 0.0.1-SNAPSHOT

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_USER_GROUP_LOG_LEVEL: "INFO"